### PR TITLE
2.0.x fix Travis error

### PR DESCRIPTION
**Pull request by Skouat**
TravisCI fails on PHP 5.5 and MySQL tests

### CODE REVIEW

**Comment by Zoddo** [comment]
Great :)

@adri1b : We can't use a default value for `$hide_attr` in `$qte->attr_select()` instead of reordering arguments?

**Comment by PastisD** [comment]
@Zoddo we can set the default value to _array()_ :)

**Comment by Zoddo** [comment]
@Skouat : Can you remove the commit cc10e96 from your pull request?

**Comment by Skouat** [comment]
Why remove it? Where is the problem with this commit?

**Comment by Zoddo** [comment]
@Skouat We will add a default value to `$hide_attr` :)

**Comment by Zoddo** [comment]
Thanks, merged!

A default value for `$hide_attr` has been added in 2f96cb8b946f0c867d67534252af9595e21de783.

**Pull request merged**
